---
- name: "Install Node.Js 13"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes

- name: "Install n"
  become: true
  npm:
    name: n
    global: yes
    production: yes


- name: " install nodejs-13.8.0"
  become: true
  shell: n 13.8.0

- name: "move env variable to /etc/profile..d/"
  become: true
  copy:
    src: myenv.sh
    dest: /etc/profile.d/

