---
- name: install nodejs
   hosts: web
   gather_facts: True
   sudo: True
   tasks:
     - name: add apt key for nodesource
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

    - name: add repo for nodesource
      apt_repository:
            repo: 'deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main' 
            update_cache: yes
   - name: "Install Node.js 13"
     become: true
     apt:
      name: ["nodejs"]
      state: latest
      update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes

- name: "move env variables to /etc/profile.d/"
  become: true
  copy:
    src: myenv.sh
    dest: /etc/profile.d/

