---
- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: "Unarchive backend files"
  unarchive:
    src: backend/artifact.tar.gz
    dest: ~/backend-app

- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend-app/dist
    cd ../
    npm install
    npm run
    sudo npm install forever -g
    sudo npm install ts-node -g
    forever start -c "ts-node -r tsconfig-paths/register -r dotenv/config src/main.ts" ./
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
